# 1. SITE SETTINGS
# This is where you can personnalize the different parameters of your website, such as its title, its description etc.
# You'll be able to call these different parameters via {{ site.yourparam }} (e.g. {{ site.title }} to retrieve the title of you site on any of your page).
# You can add to this list any new parameter you wish, and access it anywhere in the templates.

title: "mortumm.dev" # The site title
lang: en-GB # The site language
encoding: utf-8
description: "Mortumm's worklog and portfolio: Hardware enthusiasts transition to software through engineering." # The description of the site
copyright: "Â© Mortumm" # The mentions that appear in the site's footer
url: "https://mortumm.dev" # The base hostname for you site, e.g. http://mysite.com
baseurl: "/" # The subpath of your site, e.g. /blog
repo: https://github.com/Mortumm/mortumm.dev
email: me@mortumm.dev # The owner's email
# google_analytics: ""
# google_analytics_anonymize_ip: ""

# 2. SITE AVALAIBLE FUNCTIONS
darkmode: true # Allows the switch between dark and light mode
typosize: true # Allows to change the size of the font
home-posts-limit: 5 # Change the limit of posts displayed on the home page

# 3. IGNORED FILES WHILE building
# These files are essential to the building of your website, but you don't want them to be built with the others
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - simply-cyan.gemspec
  - .jekyll-cache
  - LICENSE.txt

# 4. Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: PQuod/simply-cyan-theme

# 5. Collections
# Authors's list
collections:
  categories:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "categories"

# 6. Jekyll settings
permalink: pretty # Permalink will be /YYY/MM/DD/page-name/
timezone: Europe/Helsinki
